### ISSUE TITLE
Feature request: Automatically close the docs window if it is the last window left

### ISSUE THREAD

**Issue by mcauley-penney** [amrbashir/nvim-docs-view#3]
Hey again! I'm interested in a feature and I'd like to know if it is something you're interested in as well. When closing `prev_win` with the doc window open, the doc window remains.

![doc-view-issue](https://user-images.githubusercontent.com/59481467/174909031-3863d806-bd3e-4d50-82eb-428cf55b8549.gif)

This is slightly annoying when you forget to toggle the window and want to exit. Is changing this behavior something you're open to? If so, I've already kind of started the functionality (see the below code snippet). If this is something you're open to, I'll be able to keep working on it over the course of the next week or two but don't have a lot of time in the next few days.

```lua
autocmd = vim.api.nvim_create_autocmd( "QuitPre", { 
    callback = function()                              
        if win and vim.api.nvim_win_is_valid(win) then                                           
            vim.api.nvim_win_close(win, true)          
        end                                            
    end,                                               
})                                                     
```

**Comment by amrbashir** [comment]
This seems like a valid use-case, and I don't mind adding it, but it needs to be added as an option, `autoclose_if_last` or something.

**Comment by mcauley-penney** [comment]
I built this functionality and have been testing it for a few days. It works fine and I like, though I also have been checking out how other popular plugins handle this situation and they generally don't handle it. I'm wondering now if it's just extra code for functionality that doesn't need to be provided by the plugin.

**Comment by amrbashir** [comment]
Since other plugins don't provide the option, then most users probably don't need that functionality, so I guess it is fine not to be implemented in the plugin.

**Comment by mcauley-penney** [comment]
I agree! Closing
