### ISSUE TITLE
feature request: ability to freeze doc-view

### ISSUE THREAD

**Issue by armed** [amrbashir/nvim-docs-view#6]
Sometimes I need to pin doc to sidebar and continue working with code. Currently docview is dynamic and depends on cursor position.

**Comment by amrbashir** [comment]
what do you mean by freeze exactly?

here is what I understand but feel free to correct me, you're writing some code and need to see the documentation of a function so you move the cursor to that function and the plugin shows you the documentation then you execute `:DocsViewFreeze`, then you move around and write your code and then you want to see another function documentation so you execute `:DocsViewUnFreeze` and repeat the process again?

or do you want a config option that disables the plugin auto documentation until you exectue `:DocsViewUpdate` to show documentation for the function currently under the cursor?

I prefer the latter option.

**Comment by armed** [comment]
Hey, @amrbashir. Agree with you, later is exactly what I wanted from docs-view. Displaying doc in sidebar is relevant when you want to keep it while working with the code (e.g. some complicated function/class description). For all other cases I use hover doc.

**Comment by amrbashir** [comment]
I have added `update_mode` option and `:DocsViewUpdate` command, please refer to the README.md for more info and let me know if you face any issues with them.

**Comment by armed** [comment]
Neat! Thanks a lot!
