### ISSUE TITLE
Looks like update must be defined before its use.

### ISSUE THREAD

**Issue by alexey-bataev** [amrbashir/nvim-docs-view#7]
Error executing lua callback: nvim-docs-view/lua/docs-view.lua:57: attempt to call global 'update' (a nil value)
stack traceback:                                                                                                                             nvim-docs-view/lua/docs-view.lua:57: in function <nvim-docs-view/lua/docs-view.lua:55

**Comment by amrbashir** [comment]
thanks, should be fixed now
